Add missing file to the extension package
Fixes the error

from .VesselHelpWidget import VesselHelpWidget, VesselHelpType
ModuleNotFoundError: No module named ‘RVXLiverSegmentationLib.VesselHelpWidget’